services:
  rails:
    image: chatwoot-rails-dev:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:delegated
      - packs:/app/public/packs
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    depends_on:
      - mailhog
      - vite

  sidekiq:
    image: chatwoot-sidekiq-dev:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - ./:/app:delegated
      - cache:/app/tmp/cache
      - bundle:/usr/local/bundle
    depends_on:
      - mailhog

  vite:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/vite.Dockerfile
    image: chatwoot-vite-dev:latest
    ports:
      - "3036:3036"
    volumes:
      - ./:/app:delegated
    command: ["pnpm", "exec", "vite", "dev", "--host", "0.0.0.0", "--port", "3036"]
    tty: true
    stdin_open: true

  # postgres:
  #   environment:
  #     - POSTGRES_DB=railway
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=dkSdvSLYiDNQxjTsVQuTprARLaecAPmb
  #   ports:
  #     - "5432:5432"

  # redis:
  #   command: ["sh", "-c", "redis-server --requirepass asd"]
  #   ports:
  #     - "6379:6379"

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  packs:
  cache:
  bundle:
  # postgres:
  # redis:
  node_modules: 